-- ============================================
-- Seed: inserir os 20 produtos do catálogo
-- Rodar após schema.sql no SQL Editor
-- ============================================

insert into products (id, slug, name, price, old_price, category, category_slug, image_file, description, weight, dimensions, in_stock, featured) values
(1, 'par-le-ld-botao-comando-de-som-do-volante-vectra', '(PAR-LE/LD) Botão Comando de Som do Volante Vectra', 110.00, null, 'Interruptores e Botões', 'interruptores-e-botoes', 'br-11134207-81z1k-mf3xr9g9m6me0c-400x400.jpg', 'Par de botões de comando de som do volante (lado esquerdo e direito) para Vectra. Peça rara de difícil localização no mercado nacional. Encaixe original, sem necessidade de adaptações.', '0,1 kg', '18×15×18 cm', true, true),
(2, '02-capas-dos-bracos-do-limpa-para-brisas-vw', '02 Capas dos Braços do Limpa Para-brisas VW Gol Saveiro Voyage Parati', 30.00, null, 'Limpadores', 'limpadores', 'br-11134207-81z1k-mfch2h2tut5109-400x400.jpg', 'Kit com 2 capas protetoras dos braços do limpa para-brisas para VW Gol, Saveiro, Voyage e Parati. Produto original, acabamento perfeito.', '0,05 kg', null, true, false),
(3, '2-bucha-batente-sensor-interruptor-pedal-freio', '2 Bucha Batente Sensor Interruptor Luz Pedal Freio Accord Civic Fit CRV City', 23.00, null, 'Freios', 'freios', 'br-11134207-81z1k-mf8bkc48rmro0b-3-400x400.jpg', 'Kit com 2 buchas de batente do sensor/interruptor de luz do pedal de freio. Compatível com Honda Accord, Civic, Fit, CR-V e City. Restaura o funcionamento correto das luzes de freio.', '0,03 kg', null, true, true),
(4, '2-patins-guia-do-teto-solar-fiat-stilo', '2 Patins Guia Do Teto Solar Fiat Stilo 2003/2011', 39.90, null, 'Teto Solar', 'teto-solar', 'br-11134207-81z1k-mf3cjcmux34438-1-400x400.jpg', 'Kit com 2 patins guia do teto solar para Fiat Stilo 2003 a 2011. Peça essencial para o correto deslizamento do teto solar. Original e raramente encontrada.', '0,08 kg', null, true, true),
(5, '2-pino-trava-porta-fusca-gol-voyage-parati', '2 Pino Trava Porta Fusca Brasília Variant Gol Quadrado Voyage Parati Saveiro', 10.00, null, 'Fechaduras', 'fechaduras', 'br-11134207-81z1k-merjvwgmscg01a-400x400.jpg', 'Kit com 2 pinos de trava de porta para Fusca, Brasília, Variant, Gol quadrado, Voyage, Parati e Saveiro. Produto de reposição original.', '0,02 kg', null, true, false),
(6, 'adaptador-suporte-bobina-r8-vw-audi-1-8t', 'Adaptador Suporte Bobina R8 TSI TFSI Volkswagen Audi 1.8T', 48.00, null, 'Motor', 'motor', 'br-11134207-81z1k-miaae1wck8htca-1-400x400.jpg', 'Adaptador suporte para bobina de ignição R8 em motores VW/Audi 1.8T TSI e TFSI. Permite o uso de bobinas de alta performance sem modificações estruturais.', '0,12 kg', null, true, true),
(7, 'alavanca-ajuste-banco-ford-new-fiesta-focus-motorista', 'Alavanca De Ajuste De Banco Ford New Fiesta Ford Focus 2013-2019 Motorista', 50.00, null, 'Banco e Assento', 'banco-e-assento', 'br-11134207-81z1k-meiifmwn1atedb-400x400.jpg', 'Alavanca de ajuste do banco do motorista para Ford New Fiesta e Ford Focus entre 2013 e 2019. Restaura a funcionalidade do ajuste de posição do assento.', '0,09 kg', null, true, false),
(8, 'alavanca-regulagem-banco-peugeot-206-207-motorista', 'Alavanca de Regulagem do Banco Peugeot 206 207 Motorista', 59.00, null, 'Banco e Assento', 'banco-e-assento', 'br-11134207-81z1k-mg84hl83yby812-2-400x400.jpg', 'Alavanca de regulagem do banco do motorista para Peugeot 206 e 207. Peça de reposição que restaura a funcionalidade de ajuste longitudinal do assento.', '0,11 kg', null, true, false),
(9, 'alavanca-regulagem-banco-peugeot-206-207-passageiro', 'Alavanca de Regulagem do Banco Peugeot 206 207 Passageiro', 59.00, null, 'Banco e Assento', 'banco-e-assento', 'br-11134207-81z1k-mg84hl83yby812-1-400x400.jpg', 'Alavanca de regulagem do banco do passageiro para Peugeot 206 e 207. Idêntica à do motorista, porém para o lado do passageiro.', '0,11 kg', null, true, false),
(10, 'alavanca-regulagem-encosto-banco-universal', 'Alavanca de Regulagem do Encosto do Banco – Modelo Universal', 70.90, null, 'Banco e Assento', 'banco-e-assento', 'IMG_5282-scaled-1-400x300.webp', 'Alavanca de regulagem de encosto do banco, modelo universal compatível com diversas marcas e modelos. Verifique a compatibilidade antes de comprar.', '0,15 kg', null, true, true),
(11, 'alca-ajuste-assento-banco-vw-amarok-jetta-golf', 'Alça Ajuste Assento Banco VW Amarok Jetta Golf Passat Audi', 22.00, null, 'Banco e Assento', 'banco-e-assento', 'br-11134207-81z1k-mflasvsyuk933b-400x400.jpg', 'Alça de ajuste do assento do banco para VW Amarok, Jetta, Golf, Passat e Audi. Peça plástica de reposição com encaixe original.', '0,04 kg', null, true, false),
(12, 'anel-borracha-maquina-vidro-vw-fusca', 'Anel de Borracha da Máquina de Vidro – VW Fusca', 20.00, null, 'Vedações', 'vedacoes', 'sg-11134201-824h5-me5nx2wv553552-1-400x400.jpg', 'Anel de borracha de vedação da máquina de vidro para VW Fusca. Evita a entrada de água e poeira no mecanismo do vidro elétrico/manual.', '0,02 kg', null, true, false),
(13, 'anel-cebolao-radiador-kit-10', 'Anel do Cebolão do Radiador VW Fiat GM Ford (Kit com 10)', 20.00, null, 'Motor', 'motor', 'br-11134207-81z1k-metaxw4binsz30-400x400.jpg', 'Kit com 10 anéis de borracha do cebolão do radiador. Compatível com VW, Fiat, GM e Ford. Evita vazamentos no sistema de arrefecimento.', '0,03 kg', null, true, false),
(14, 'arremate-acabamento-friso-porta-gol-voyage', 'Arremate Acabamento Friso Porta Do Gol Voyage Quadrado Par', 40.00, null, 'Tampas e Acabamentos', 'tampas-e-acabamentos', 'br-11134207-81z1k-mfcid6cr81dw5d-1-400x400.jpg', 'Par de arremates de acabamento do friso da porta para Gol e Voyage quadrado (1ª e 2ª geração). Restitui a estética original do veículo.', '0,07 kg', null, true, false),
(15, 'bloco-condensador-distribuidor-vectra-astra', 'Bloco Condensador do Distribuidor – Chevrolet Vectra/Astra/Omega', 249.00, null, 'Motor', 'motor', 'vec1-400x400.png', 'Bloco condensador do distribuidor para Chevrolet Vectra, Astra e Omega até 1996. Peça técnica de alta complexidade e raridade. Solução definitiva para falhas no sistema de ignição.', '0,3 kg', '15×12×8 cm', true, true),
(16, 'borracha-vedacao-base-antena-teto', 'Borracha de Vedação da Base da Antena de Teto', 60.00, null, 'Vedações', 'vedacoes', 'br-11134207-81z1k-mfb35vx06l1hcb-400x400.jpg', 'Borracha de vedação da base da antena de teto para Gol GTI quadrado (1ª geração). Elimina vazamentos de água pelo furo da antena.', '0,04 kg', null, true, false),
(17, 'botao-alavanca-cambio-automatico-ford-focus', 'Botão Alavanca Do Câmbio Automático Ford Focus Ecosport', 60.00, null, 'Câmbio', 'cambio', 'br-11134207-81z1k-mf404hn4ov7q2e-1-400x400.jpg', 'Botão de acionamento da alavanca do câmbio automático para Ford Focus e Ecosport. Restaura a funcionalidade e aparência original da alavanca de câmbio.', '0,05 kg', null, true, true),
(18, 'botao-alavanca-cambio-automatico-honda-civic', 'Botão Alavanca Do Câmbio Automático Honda Civic', 95.00, null, 'Câmbio', 'cambio', 'br-11134207-81z1k-mf8bkc49026ce3-400x400.jpg', 'Botão de acionamento da alavanca do câmbio automático para Honda Civic. Acabamento original, encaixe perfeito sem adaptações.', '0,06 kg', null, true, false),
(19, 'alavanca-regulagem-banco-peugeot-par', 'Alavanca de Regulagem do Banco Peugeot 206 207 Motorista e Passageiro', 130.00, null, 'Banco e Assento', 'banco-e-assento', 'placeholder', 'Par completo (motorista + passageiro) de alavancas de regulagem do banco para Peugeot 206 e 207. Ideal para quem precisa trocar os dois lados.', '0,22 kg', null, true, false),
(20, 'adaptador-led-h1-farol-astra', 'Adaptador para Lâmpadas de LED H1 e H7 Farol Astra H1', 10.00, 34.90, 'Iluminação', 'iluminacao', 'placeholder', 'Adaptador para instalação de lâmpadas LED H1 no farol do Astra. Permite o uso de lâmpadas de LED sem modificações no farol original.', '0,02 kg', null, true, false);

-- Reset sequence to continue after id 20
select setval('products_id_seq', 20);
