-- Tabela de imagens de produtos (suporte a múltiplas fotos por produto)
CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  alt_text TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Garantir que cada produto tenha no máximo uma imagem com sort_order=0 (principal)
  UNIQUE (product_id, sort_order)
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_sort_order ON product_images(product_id, sort_order);

-- RLS (Row Level Security)
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;

-- Policy: pública pode ler
CREATE POLICY "Imagens de produtos visíveis publicamente"
  ON product_images FOR SELECT
  TO anon, authenticated
  USING (true);

-- Policy: service role tem acesso total
CREATE POLICY "Service role pode gerenciar imagens de produtos"
  ON product_images FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Comments para documentação
COMMENT ON TABLE product_images IS 'Múltiplas imagens por produto. sort_order=0 é a imagem principal (capa)';
COMMENT ON COLUMN product_images.url IS 'URL completa da imagem (Supabase Storage ou externa)';
COMMENT ON COLUMN product_images.alt_text IS 'Texto alternativo para acessibilidade e SEO';
COMMENT ON COLUMN product_images.sort_order IS 'Ordem de exibição. 0 = imagem principal (capa)';
